<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3quotes"
 *
 * Auto generated by Extension Builder 2018-03-26
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Quotes database',
    'description' => 'A database with quotes which are displayed on the webpage in various ways, based on extbase & fluid for TYPO3 CMS.',
    'category' => 'plugin',
    'author' => 'Kasper Skårhøj (2002), David Bruchmann (2018)',
    'author_email' => 'kasper@typo3.com, david.bruchmann@gmail.com',
    'state' => 'beta',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '2.0.4',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-9.1.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
